name: mezcalmos
description: A local business networking app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 9.11.0+90

environment:
  sdk: ">=2.17.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  photo_view: ^0.14.0
  google_fonts: ^3.0.1
  http: ^0.13.3
  url_launcher: ^6.0.9
  bot_toast: ^4.0.3
  get: ^4.3.8
  qlevar_router: ^1.6.3
  get_storage: ^2.0.3
  image: ^3.0.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.2.0
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  toggle_switch: ^2.0.1
  firebase_auth: ^4.2.4
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  firebase_dynamic_links: ^5.0.11
  cloud_functions: ^4.0.7
  flutter_local_notifications: ^13.0.0
  sliding_up_panel: ^2.0.0+1
  location: ^4.2.0
  shimmer: ^2.0.0
  pin_code_fields: ^7.2.0
  sizer: ^2.0.15
  intl: ^0.17.0
  device_preview: ^1.1.0
  webview_flutter: ^4.0.1
  google_maps_flutter_platform_interface: ^2.2.4
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.0.0
  google_maps_flutter: ^2.0.9
  geocoding: ^2.0.1
  flutter_polyline_points: ^1.0.0
  badges: ^2.0.2
  font_awesome_flutter: ^10.1.0
  flutter_stripe: ^7.0.0
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  flutter_email_sender: ^5.1.0
  flutter_callkit_incoming: ^1.0.3+1
  charts_flutter: ^0.12.0
  soundpool: ^2.2.0
  permission_handler: ^10.0.0
  image_downloader: 0.31.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.4
  progress_indicators: ^1.0.0
  lottie: ^2.2.0
  flutter_image_compress: ^1.1.0
  rive: ^0.10.0
  flutter_rating_bar: ^4.0.1
  ionicons: ^0.2.1
  store_redirect: ^2.0.1
  grouped_list: ^5.1.1
  connectivity_plus: ^3.0.3
  dart_ping: ^8.0.1
  flutter_countdown_timer: ^4.1.0
  crypto: ^3.0.0-nullsafety.0
  graphql:
    path: ./packages/graphql
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1
  html: ^0.15.0
  image_compression_flutter: ^1.0.2
  agora_rtc_engine: 6.1.0


dependency_overrides:
  web_socket_channel: 2.2.0
  #firebase_core_platform_interface: 4.5.2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  graphql_codegen: ^0.11.2
  jwt_decoder: ^2.0.1
  jaguar_jwt: ^3.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/ios.png"
  image_path_android: "assets/icons/android.png"

flutter:

  uses-material-design: true

# Assets
  assets:
    - assets/images/
    - assets/images/customer/
    - assets/images/shared/
    - assets/images/laundryApp/
    - assets/images/shared/notifications/
    - assets/images/shared/notifications/laundry/
    - assets/images/deliveryAdmin/
    - assets/images/customer/restaurants/
    - assets/images/customer/taxi/
    - assets/images/customer/laundry/
    - assets/images/customer/rental/
    - assets/fonts/
    - assets/i18n/
    - assets/animation/
    - assets/sounds/
    - assets/icons/appstore.png
    - "assets/images/customer/rental/"


# Fonts
  fonts:
    - family: psr
      fonts:
        - asset: assets/fonts/psr.ttf
    - family: psb
      fonts:
        - asset: assets/fonts/psb.ttf
    - family: psi
      fonts:
        - asset: assets/fonts/psi.ttf
    - family: psbi
      fonts:
        - asset: assets/fonts/psbi.ttf
    - family: MezcalmosIcons
      fonts:
        - asset: assets/fonts/MezcalmosIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
            